# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Lint/AmbiguousOperator
Lint/AmbiguousOperator:
  Enabled: true

# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Lint/AmbiguousRegexpLiteral
Lint/AmbiguousRegexpLiteral:
  Enabled: true

# Configuration parameters: AllowSafeAssignment.
# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Lint/AssignmentInCondition
Lint/AssignmentInCondition:
  Enabled: false

# Cop supports --auto-correct.
# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Lint/BlockAlignment
Lint/BlockAlignment:
  Enabled: true

# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Lint/Debugger
Lint/Debugger:
  Enabled: true

# Configuration parameters: AlignWith, SupportedStyles.
# http://www.rubydoc.info/gems/rubocop/0.27.0/RuboCop/Cop/Lint/DefEndAlignment
Lint/DefEndAlignment:
  Enabled: true

# Cop supports --auto-correct.
# http://www.rubydoc.info/github/bbatsov/rubocop/master/Rubocop/Cop/Lint/DeprecatedClassMethods
Lint/DeprecatedClassMethods:
  Enabled: true

# Configuration parameters: AlignWith, SupportedStyles.
# http://www.rubydoc.info/github/bbatsov/rubocop/master/Rubocop/Cop/Lint/EndAlignment
Lint/EndAlignment:
  Enabled: true

# http://www.rubydoc.info/github/bbatsov/rubocop/master/Rubocop/Cop/Lint/HandleExceptions
Lint/HandleExceptions:
  Enabled: true

# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Lint/LiteralInCondition
Lint/LiteralInCondition:
  Enabled: false

# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Lint/ParenthesesAsGroupedExpression
Lint/ParenthesesAsGroupedExpression:
  Enabled: false

# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Lint/RescueException
Lint/RescueException:
  Enabled: true

# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Lint/ShadowingOuterLocalVariable
Lint/ShadowingOuterLocalVariable:
  Enabled: true

# Cop supports --auto-correct.
# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Lint/StringConversionInInterpolation
Lint/StringConversionInInterpolation:
  Enabled: true

# http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/UnderscorePrefixedVariableName
Lint/UnderscorePrefixedVariableName:
  Enabled: true

# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Lint/UnreachableCode
Lint/UnreachableCode:
  Enabled: true

# Cop supports --auto-correct.
# http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/UnusedBlockArgument
Lint/UnusedBlockArgument:
  Enabled: true

# Cop supports --auto-correct.
# http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/UnusedMethodArgument
Lint/UnusedMethodArgument:
  Enabled: true

# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Lint/UselessAccessModifier
Lint/UselessAccessModifier:
  Enabled: true

# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Lint/UselessAssignment
Lint/UselessAssignment:
  Enabled: true

# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Lint/Void
Lint/Void:
  Enabled: true

# http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Metrics/AbcSize
Metrics/AbcSize:
  Max: 140

# http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Metrics/BlockNesting
Metrics/BlockNesting:
  Max: 3

# Configuration parameters: CountComments.
# http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Metrics/ClassLength
Metrics/ClassLength:
  Max: 500

# http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Metrics/CyclomaticComplexity
Metrics/CyclomaticComplexity:
  Max: 20

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 140

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 50

# Configuration parameters: CountKeywordArgs.
# http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Metrics/ParameterLists
Metrics/ParameterLists:
  Max: 4

Metrics/PerceivedComplexity:
  Max: 30

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AccessModifierIndentation:
  Enabled: true

# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/AccessorMethodName
Style/AccessorMethodName:
  Enabled: true

# Cop supports --auto-correct.
Style/Alias:
  Enabled: true

# Cop supports --auto-correct.
# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/AlignArray
Style/AlignArray:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle, SupportedLastArgumentHashStyles.
Style/AlignHash:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AlignParameters:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/AndOr
Style/AndOr:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/BarePercentLiterals
Style/BarePercentLiterals:
  Enabled: true

# Cop supports --auto-correct.
Style/BlockEndNewline:
  Enabled: true

# Cop supports --auto-correct.
# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/Blocks
# warning: auto correction on this causes app break
Style/Blocks:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/BracesAroundHashParameters
Style/BracesAroundHashParameters:
  Enabled: true

# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/CaseEquality
Style/CaseEquality:
  Enabled: true

# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep.
Style/CaseIndentation:
  Enabled: true

# Configuration parameters: EnforcedStyle, SupportedStyles.
# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/ClassAndModuleChildren
Style/ClassAndModuleChildren:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# http://www.rubydoc.info/gems/rubocop/0.27.0/RuboCop/Cop/Style/ClassCheck
Style/ClassCheck:
  Enabled: true

Style/ClassVars:
  Enabled: true

# Cop supports --auto-correct.
Style/ColonMethodCall:
  Enabled: true

# Configuration parameters: Keywords.
Style/CommentAnnotation:
  Enabled: true

# Cop supports --auto-correct.
Style/CommentIndentation:
  Enabled: true

# Cop supports --auto-correct.
Style/DefWithParentheses:
  Enabled: true

# Cop supports --auto-correct.
Style/DeprecatedHashMethods:
  Enabled: true

Style/Documentation:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/DotPosition:
  Enabled: true

Style/DoubleNegation:
  Enabled: true

# http://www.rubydoc.info/gems/rubocop/0.27.0/RuboCop/Cop/Style/EachWithObject
Style/EachWithObject:
  Enabled: true

# Cop supports --auto-correct.
Style/ElseAlignment:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: AllowAdjacentOneLineDefs.
# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/EmptyLineBetweenDefs
Style/EmptyLineBetweenDefs:
  Enabled: true

# Cop supports --auto-correct.
Style/EmptyLines:
  Enabled: true

# Cop supports --auto-correct.
Style/EmptyLinesAroundAccessModifier:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundClassBody:
  Enabled: true

# Cop supports --auto-correct.
Style/EmptyLinesAroundMethodBody:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundModuleBody:
  Enabled: true

# Cop supports --auto-correct.
Style/EmptyLiteral:
  Enabled: true

# Configuration parameters: Exclude.
# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/FileName
Style/FileName:
  Enabled: true

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FormatString:
  Enabled: true

# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Enabled: true

# Configuration parameters: MinBodyLength.
# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/GuardClause
Style/GuardClause:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/HashSyntax:
  Enabled: true

# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: true

# Cop supports --auto-correct.
Style/IndentArray:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/IndentHash:
  Enabled: true

# Cop supports --auto-correct.
Style/IndentationConsistency:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: Width.
Style/IndentationWidth:
  Enabled: true

Style/Lambda:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/LambdaCall:
  Enabled: true

# Cop supports --auto-correct.
Style/LeadingCommentSpace:
  Enabled: true

# Cop supports --auto-correct.
Style/LineEndConcatenation:
  Enabled: true

# Cop supports --auto-correct.
Style/MethodCallParentheses:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MethodDefParentheses:
  Enabled: true

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MethodName:
  Enabled: true

Style/ModuleFunction:
  Enabled: true

# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/MultilineBlockChain
Style/MultilineBlockChain:
  Enabled: true

# Cop supports --auto-correct.
Style/MultilineBlockLayout:
  Enabled: true

# Cop supports --auto-correct.
Style/MultilineIfThen:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MultilineOperationIndentation:
  Enabled: true

# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/MultilineTernaryOperator
Style/MultilineTernaryOperator:
  Enabled: true

# Cop supports --auto-correct.
Style/NegatedIf:
  Enabled: true

# Cop supports --auto-correct.
Style/NegatedWhile:
  Enabled: true

Style/NestedTernaryOperator:
  Enabled: true

# Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
Style/Next:
  Enabled: true

# Cop supports --auto-correct.
# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/NilComparison
Style/NilComparison:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: IncludeSemanticChanges.
Style/NonNilCheck:
  Enabled: true

# Cop supports --auto-correct.
Style/Not:
  Enabled: true

# Cop supports --auto-correct.
# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/NumericLiterals
Style/NumericLiterals:
  MinDigits: 4

Style/OneLineConditional:
  Enabled: true

# http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/OpMethod
Style/OpMethod:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: AllowSafeAssignment.
Style/ParenthesesAroundCondition:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/PercentLiteralDelimiters
Style/PercentLiteralDelimiters:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/PercentQLiterals:
  Enabled: true

# Cop supports --auto-correct.
Style/PerlBackrefs:
  Enabled: true

# Configuration parameters: NamePrefix, NamePrefixBlacklist.
# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/PredicateName
Style/PredicateName:
  Enabled: true

# Cop supports --auto-correct.
Style/Proc:
  Enabled: true

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/RaiseArgs:
  Enabled: true

# Cop supports --auto-correct.
Style/RedundantBegin:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Enabled: true

# Cop supports --auto-correct.
Style/RedundantSelf:
  Enabled: true

# Configuration parameters: MaxSlashes.
Style/RegexpLiteral:
  Enabled: true

Style/RescueModifier:
  Enabled: true

# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/SelfAssignment
Style/SelfAssignment:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: AllowAsExpressionSeparator.
Style/Semicolon:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SignalException:
  Enabled: true

# Configuration parameters: Methods.
Style/SingleLineBlockParams:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: AllowIfMethodIsEmpty.
Style/SingleLineMethods:
  Enabled: true

# Cop supports --auto-correct.
Style/SingleSpaceBeforeFirstArg:
  Enabled: false

# Cop supports --auto-correct.
Style/SpaceAfterColon:
  Enabled: true

# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Enabled: true

# Cop supports --auto-correct.
Style/SpaceAfterControlKeyword:
  Enabled: true

# Cop supports --auto-correct.
Style/SpaceAfterNot:
  Enabled: true

# Cop supports --auto-correct.
Style/SpaceAfterSemicolon:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/SpaceAroundEqualsInParameterDefault
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: true

# Cop supports --auto-correct.
Style/SpaceAroundOperators:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SpaceBeforeBlockBraces:
  Enabled: false

# Cop supports --auto-correct.
Style/SpaceBeforeComma:
  Enabled: false

# Cop supports --auto-correct.
Style/SpaceBeforeComment:
  Enabled: true

# Cop supports --auto-correct.
Style/SpaceBeforeModifierKeyword:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
Style/SpaceInsideBlockBraces:
  Enabled: false

# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
Style/SpaceInsideHashLiteralBraces:
  Enabled: false

# Cop supports --auto-correct.
Style/SpaceInsideParens:
  Enabled: false

# Cop supports --auto-correct.
# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/SpecialGlobalVars
Style/SpecialGlobalVars:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/StringLiterals
Style/StringLiterals:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiteralsInInterpolation:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
# http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/SymbolProc
Style/SymbolProc:
  Enabled: true

# Cop supports --auto-correct.
Style/Tab:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/TrailingBlankLines:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline, SupportedStyles.
Style/TrailingComma:
  Enabled: true

# Cop supports --auto-correct.
Style/TrailingWhitespace:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: ExactNameMatch, AllowPredicates, AllowDSLWriters, Whitelist.
Style/TrivialAccessors:
  Enabled: true

Style/UnlessElse:
  Enabled: true

# Cop supports --auto-correct.
# http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/UnneededCapitalW
Style/UnneededCapitalW:
  Enabled: true

# Cop supports --auto-correct.
Style/UnneededPercentQ:
  Enabled: true

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/VariableName:
  Enabled: true

# Cop supports --auto-correct.
Style/WhileUntilDo:
  Enabled: true

# Configuration parameters: MaxLineLength.
Style/WhileUntilModifier:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: WordRegex.
# http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/WordArray
Style/WordArray:
  MinSize: 3